
services:
  flask:
    build: .
    ports:
      - "5000:5000"

  locust:
    build: ./locust
    depends_on:
      - flask
    ports:
      - "8089:8089"
    volumes:
       - ./locust:/locust/locustfile.py:ro
      #- ./locust/:/locust/:ro

    command: ["locust", "--host=http://flask:5000"]
